[pytest]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
addopts = -vs --alluredir=./outputs/report/allure_results --clean-alluredir
testpaths = projects/workspace/testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = INFO
markers =
    smoke: smoke test cases
    login: login test cases
    account: account test cases

filterwarnings =
    ignore:Module already imported so cannot be rewritten:pytest.PytestAssertRewriteWarning
